// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxotrymbceudxfmugsyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4b3RyeW1iY2V1ZHhmbXVnc3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0Njk3NjQsImV4cCI6MjA3MDA0NTc2NH0.bhhe2frF2IaweW9QMUqjvidKwTdL7-bMJd-5BEjdaM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});